import { test, expect } from "@playwright/test"
const TITLE = '[data-testid="product-title"]'
const CARD = ".product-card"

/**
 * EXPECTED PRODUCT LISTS — data validation baseline.
 * When products are added, removed, or reordered, update these lists.
 * Tests fail when display changes — review and update intentionally.
 */

test("Spices parent — exhaustive product list validation", async ({ page }) => {
  await page.goto("/categories/spices"); await page.waitForSelector(CARD, { timeout: 60000 })
  const titles = await page.$$eval(TITLE, (els) => els.map((el) => el.textContent?.trim()).filter(Boolean) as string[])

  // Log for audit
  console.log(`Spices: ${titles.length} products`)
  titles.forEach((t, i) => console.log(`  ${i + 1}. ${t}`))

  // Count verification
  expect(titles.length).toBeGreaterThanOrEqual(155)

  // --- Spices & Herbs (101 products) ---
  expect(titles).toContain("Natco - Ajwan Seeds 300g")
  expect(titles).toContain("Natco - Ajwan Seeds Jar 100g")
  expect(titles).toContain("Natco - Amchoor Powder 400g")
  expect(titles).toContain("Natco - Amchoor Powder Jar 100g")
  expect(titles).toContain("Natco - Aniseed Star Jar 40g")
  expect(titles).toContain("Natco - Asafoetida (Hing) Jar 100g")
  expect(titles).toContain("Natco - Basil Jar 25g")
  expect(titles).toContain("Natco - Bay Leaves Jar 10g")
  expect(titles).toContain("Natco - Black Pepper Coarse 100g")
  expect(titles).toContain("Natco - Black Pepper Coarse 1kg")
  expect(titles).toContain("Natco - Black Pepper Coarse 300g")
  expect(titles).toContain("Natco - Black Pepper Ground 400g")
  expect(titles).toContain("Natco - Black Pepper Whole 1kg")
  expect(titles).toContain("Natco - Black Pepper Whole 300g")
  expect(titles).toContain("Natco - Cardamom Green 200g")
  expect(titles).toContain("Natco - Cardamom Green Ground 50g")
  expect(titles).toContain("Natco - Cardamom Green Jar 50g")
  expect(titles).toContain("Natco - Cardamom Seeds 100g")
  expect(titles).toContain("Natco - Cassia (Dalchini) 400g")
  expect(titles).toContain("Natco - Cassia (Dalchini) Jar 50g")
  expect(titles).toContain("Natco - Chilli Crushed 300g")
  expect(titles).toContain("Natco - Chilli Crushed Jar 80g")
  expect(titles).toContain("Natco - Chilli Powder 100g")
  expect(titles).toContain("Natco - Chilli Powder 1kg")
  expect(titles).toContain("Natco - Chilli Powder Extra Hot 400g")
  expect(titles).toContain("Natco - Chilli Powder Hot Jar 100g")
  expect(titles).toContain("Natco - Chilli Powder Kashmiri 100g")
  expect(titles).toContain("Natco - Chilli Powder Kashmiri 400g")
  expect(titles).toContain("Natco - Chilli Whole Birdseye 150g")
  expect(titles).toContain("Natco - Chilli Whole Stemless 200g")
  expect(titles).toContain("Natco - Chinese 5 Spice 100g")
  expect(titles).toContain("Natco - Cinnamon Ground Jar 100g")
  expect(titles).toContain("Natco - Cinnamon Sticks 50g")
  expect(titles).toContain("Natco - Cloves 200g")
  expect(titles).toContain("Natco - Cloves Ground 50g")
  expect(titles).toContain("Natco - Cloves Jar 50g")
  expect(titles).toContain("Natco - Coriander Ground 400g")
  expect(titles).toContain("Natco - Coriander Ground Jar 70g")
  expect(titles).toContain("Natco - Coriander Leaves Jar 25g")
  expect(titles).toContain("Natco - Coriander Seeds 300g")
  expect(titles).toContain("Natco - Coriander Seeds Jar 60g")
  expect(titles).toContain("Natco - Coriander Seeds Jar 65g")
  expect(titles).toContain("Natco - Cumin Ground 100g")
  expect(titles).toContain("Natco - Cumin Ground 400g")
  expect(titles).toContain("Natco - Cumin Seeds 400g")
  expect(titles).toContain("Natco - Cumin Seeds Black 100g")
  expect(titles).toContain("Natco - Curry Leaves 100g")
  expect(titles).toContain("Natco - Curry Powder 400g")
  expect(titles).toContain("Natco - Curry Powder Hot 100g")
  expect(titles).toContain("Natco - Curry Powder Hot 400g")
  expect(titles).toContain("Natco - Dried Tarragon 25g")
  expect(titles).toContain("Natco - Fennel Seeds 400g")
  expect(titles).toContain("Natco - Garam Masala Jar 80g")
  expect(titles).toContain("Natco - Garlic Flakes 100g")
  expect(titles).toContain("Natco - Garlic Powder 100g")
  expect(titles).toContain("Natco - Ginger Powder 100g")
  expect(titles).toContain("Natco - Kala Namak 100g")
  expect(titles).toContain("Natco - Kala Namak 300g")
  expect(titles).toContain("Natco - Kalwanji (Nigella) Seeds 300g")
  expect(titles).toContain("Natco - Kasuri Methi Leaves 100g")
  expect(titles).toContain("Natco - Mace Ground 50g")
  expect(titles).toContain("Natco - Marjoram Jar 20g")
  expect(titles).toContain("Natco - Methi Seeds Fenugreek 400g")
  expect(titles).toContain("Natco - Mint Jar 30g")
  expect(titles).toContain("Natco - Mixed Herbs Jar 25g")
  expect(titles).toContain("Natco - Mustard Seeds 400g")
  expect(titles).toContain("Natco - Nutmeg Ground 50g")
  expect(titles).toContain("Natco - Oregano Jar 25g")
  expect(titles).toContain("Natco - Panchpuran (5 Whole Spice) 1kg")
  expect(titles).toContain("Natco - Paprika Powder 400g")
  expect(titles).toContain("Natco - Parsley Jar 25g")
  expect(titles).toContain("Natco - Rosemary Jar 40g")
  expect(titles).toContain("Natco - Saffron 1g")
  expect(titles).toContain("Natco - Sage Jar 25g")
  expect(titles).toContain("Natco - Takmuria (Basil Seeds) 100g")
  expect(titles).toContain("Natco - Tamarind Slab 200g")
  expect(titles).toContain("Natco - Tamarind Wet 400g")
  expect(titles).toContain("Natco - Tandoori Masala Jar 100g")
  expect(titles).toContain("Natco - Turmeric Powder 400g")
  expect(titles).toContain("Natco - White Pepper Ground 100g")
  expect(titles).toContain("Natco - Whole Birdseye Chilli Jar 40g")
  expect(titles).toContain("Natco - Whole Birdseye Chilli Jar 50g")
  expect(titles).toContain("Natco - Yellow Mustard Seeds 300g")

  // TRS spices & herbs
  expect(titles).toContain("TRS Coarse Black Pepper")
  expect(titles).toContain("TRS Coriander Powder (Dhania)")
  expect(titles).toContain("TRS Coriander Seeds (Whole Dhania)")
  expect(titles).toContain("TRS Crushed Chilli")
  expect(titles).toContain("TRS Cumin Powder")
  expect(titles).toContain("TRS Cumin Seeds")
  expect(titles).toContain("TRS Fennel Seeds")
  expect(titles).toContain("TRS Fenugreek Leaves")
  expect(titles).toContain("TRS Fenugreek Seeds")
  expect(titles).toContain("TRS Garlic Powder")
  expect(titles).toContain("TRS Ginger Powder")
  expect(titles).toContain("TRS Green Cardamom")
  expect(titles).toContain("TRS Mango Powder (Amchoor)")
  expect(titles).toContain("TRS Paprika Powder")
  expect(titles).toContain("TRS Pomegranate Powder (Anardana)")
  expect(titles).toContain("TRS Pomegranate Seeds (Anardana Whole)")
  expect(titles).toContain("TRS Tumeric Powder")
  expect(titles).toContain("TRS Whole Cinnamon (Dalchini)")

  // --- Spice & Herb Jars (18 products) ---
  expect(titles).toContain("Natco - Black Pepper Ground Jar 100g")
  expect(titles).toContain("Natco - Black Pepper Whole Jar 100g")
  expect(titles).toContain("Natco - Cumin Ground Jar 70g")
  expect(titles).toContain("Natco - Cumin Seeds Jar 100g")
  expect(titles).toContain("Natco - Curry Powder Medium Jar 100g")
  expect(titles).toContain("Natco - Fennel Seeds Jar 100g")
  expect(titles).toContain("Natco - Garlic Powder Jar 100g")
  expect(titles).toContain("Natco - Ground Ginger Jar 70g")
  expect(titles).toContain("Natco - Kalwanji (Nigella) Seeds Jar 100g")
  expect(titles).toContain("Natco - Methi Leaves Jar 10g")
  expect(titles).toContain("Natco - Methi Seeds Jar 100g")
  expect(titles).toContain("Natco - Mustard Seeds Black Jar 100g")
  expect(titles).toContain("Natco - Nutmeg Ground Jar 100g")
  expect(titles).toContain("Natco - Nutmeg Whole Jar 100g")
  expect(titles).toContain("Natco - Paprika Powder Jar 100g")
  expect(titles).toContain("Natco - Tamarind Paste Jar 250g")
  expect(titles).toContain("Natco - Turmeric Powder Jar 100g")
  expect(titles).toContain("Natco - White Pepper Ground Jar 100g")

  // --- Spice Blends & Mixes (19 products) ---
  expect(titles).toContain("Natco - All Purpose Seasoning 100g")
  expect(titles).toContain("Natco - All Purpose Seasoning 400g")
  expect(titles).toContain("Natco - Anardana Powder Mangal 100g")
  expect(titles).toContain("Natco - Biryani Masala Mangal 50g")
  expect(titles).toContain("Natco - Chana Masala Mangal 100g")
  expect(titles).toContain("Natco - Chat Masala Mangal 100g")
  expect(titles).toContain("Natco - Chicken Masala Mangal 100g")
  expect(titles).toContain("Natco - Garam Masala 400g")
  expect(titles).toContain("Natco - Meat Masala Mangal 100g")
  expect(titles).toContain("Natco - Mixed Masala Whole 300g")
  expect(titles).toContain("Natco - Pavbhaji Masala Mangal 100g")
  expect(titles).toContain("Natco - Pickle Masala Mangal 125g")
  expect(titles).toContain("Natco - Sambhar Masala Mangal 100g")
  expect(titles).toContain("Natco - Tandoori Masala 400g")
  expect(titles).toContain("Natco - Thecha Chilli Paste 300g")

  // TRS blends
  expect(titles).toContain("TRS Garam Masala")
  expect(titles).toContain("TRS Hot Madras Curry")
  expect(titles).toContain("TRS Mild Madras Curry Powder")
  expect(titles).toContain("TRS Sarson Ka Saag (Spiced Mustard Greens Curry)")

  // --- Food Colourings & Essences (19 products) ---
  expect(titles).toContain("Natco - Almond Flavouring Essence 28ml")
  expect(titles).toContain("Natco - Coconut Flavouring Essence 28ml")
  expect(titles).toContain("Natco - Green Food Colouring - Liquid 28ml")
  expect(titles).toContain("Natco - Green Food Colouring - Powder 25g")
  expect(titles).toContain("Natco - Kevda Water 310ml")
  expect(titles).toContain("Natco - Lemon Juice 1 Ltr")
  expect(titles).toContain("Natco - Lemon Juice 500ml")
  expect(titles).toContain("Natco - Lemon Juice with Essential Oil 200ml")
  expect(titles).toContain("Natco - Orange Food Colouring - Liquid 28ml")
  expect(titles).toContain("Natco - Orange Food Colouring - Powder 25g")
  expect(titles).toContain("Natco - Pineapple Flavouring Essence 28ml")
  expect(titles).toContain("Natco - Red Food Colouring - Liquid 28ml")
  expect(titles).toContain("Natco - Red Food Colouring - Powder 25g")
  expect(titles).toContain("Natco - Rose Flavouring Essence 28ml")
  expect(titles).toContain("Natco - Rose Syrup 725ml")
  expect(titles).toContain("Natco - Rose Water 310ml")
  expect(titles).toContain("Natco - Strawberry Flavouring Essence 28ml")
  expect(titles).toContain("Natco - Vanilla Flavouring Essence 28ml")
  expect(titles).toContain("Natco - Yellow Food Colouring - Powder 25g")

  // --- Sugar & Jaggery (4 products) ---
  expect(titles).toContain("Natco - Demerara Sugar 1.5kg")
  expect(titles).toContain("Natco - Demerara Sugar 500g")
  expect(titles).toContain("Natco - Jaggery 500g")
  expect(titles).toContain("Natco - Sugar Candy 375g")
})

test("Spices — Spices & Herbs child", async ({ page }) => {
  await page.goto("/categories/spices-herbs"); await page.waitForSelector(CARD, { timeout: 60000 })
  const titles = await page.$$eval(TITLE, (els) => els.map((el) => el.textContent?.trim()).filter(Boolean) as string[])
  console.log(`Spices & Herbs: ${titles.length}`)
  titles.forEach((t, i) => console.log(`  ${i + 1}. ${t}`))

  // Count verification
  expect(titles.length).toBeGreaterThanOrEqual(95)

  // --- All 101 Spices & Herbs products ---
  expect(titles).toContain("Natco - Ajwan Seeds 300g")
  expect(titles).toContain("Natco - Ajwan Seeds Jar 100g")
  expect(titles).toContain("Natco - Amchoor Powder 400g")
  expect(titles).toContain("Natco - Amchoor Powder Jar 100g")
  expect(titles).toContain("Natco - Aniseed Star Jar 40g")
  expect(titles).toContain("Natco - Asafoetida (Hing) Jar 100g")
  expect(titles).toContain("Natco - Basil Jar 25g")
  expect(titles).toContain("Natco - Bay Leaves Jar 10g")
  expect(titles).toContain("Natco - Black Pepper Coarse 100g")
  expect(titles).toContain("Natco - Black Pepper Coarse 1kg")
  expect(titles).toContain("Natco - Black Pepper Coarse 300g")
  expect(titles).toContain("Natco - Black Pepper Ground 400g")
  expect(titles).toContain("Natco - Black Pepper Whole 1kg")
  expect(titles).toContain("Natco - Black Pepper Whole 300g")
  expect(titles).toContain("Natco - Cardamom Green 200g")
  expect(titles).toContain("Natco - Cardamom Green Ground 50g")
  expect(titles).toContain("Natco - Cardamom Green Jar 50g")
  expect(titles).toContain("Natco - Cardamom Seeds 100g")
  expect(titles).toContain("Natco - Cassia (Dalchini) 400g")
  expect(titles).toContain("Natco - Cassia (Dalchini) Jar 50g")
  expect(titles).toContain("Natco - Chilli Crushed 300g")
  expect(titles).toContain("Natco - Chilli Crushed Jar 80g")
  expect(titles).toContain("Natco - Chilli Powder 100g")
  expect(titles).toContain("Natco - Chilli Powder 1kg")
  expect(titles).toContain("Natco - Chilli Powder Extra Hot 400g")
  expect(titles).toContain("Natco - Chilli Powder Hot Jar 100g")
  expect(titles).toContain("Natco - Chilli Powder Kashmiri 100g")
  expect(titles).toContain("Natco - Chilli Powder Kashmiri 400g")
  expect(titles).toContain("Natco - Chilli Whole Birdseye 150g")
  expect(titles).toContain("Natco - Chilli Whole Stemless 200g")
  expect(titles).toContain("Natco - Chinese 5 Spice 100g")
  expect(titles).toContain("Natco - Cinnamon Ground Jar 100g")
  expect(titles).toContain("Natco - Cinnamon Sticks 50g")
  expect(titles).toContain("Natco - Cloves 200g")
  expect(titles).toContain("Natco - Cloves Ground 50g")
  expect(titles).toContain("Natco - Cloves Jar 50g")
  expect(titles).toContain("Natco - Coriander Ground 400g")
  expect(titles).toContain("Natco - Coriander Ground Jar 70g")
  expect(titles).toContain("Natco - Coriander Leaves Jar 25g")
  expect(titles).toContain("Natco - Coriander Seeds 300g")
  expect(titles).toContain("Natco - Coriander Seeds Jar 60g")
  expect(titles).toContain("Natco - Coriander Seeds Jar 65g")
  expect(titles).toContain("Natco - Cumin Ground 100g")
  expect(titles).toContain("Natco - Cumin Ground 400g")
  expect(titles).toContain("Natco - Cumin Seeds 400g")
  expect(titles).toContain("Natco - Cumin Seeds Black 100g")
  expect(titles).toContain("Natco - Curry Leaves 100g")
  expect(titles).toContain("Natco - Curry Powder 400g")
  expect(titles).toContain("Natco - Curry Powder Hot 100g")
  expect(titles).toContain("Natco - Curry Powder Hot 400g")
  expect(titles).toContain("Natco - Dried Tarragon 25g")
  expect(titles).toContain("Natco - Fennel Seeds 400g")
  expect(titles).toContain("Natco - Garam Masala Jar 80g")
  expect(titles).toContain("Natco - Garlic Flakes 100g")
  expect(titles).toContain("Natco - Garlic Powder 100g")
  expect(titles).toContain("Natco - Ginger Powder 100g")
  expect(titles).toContain("Natco - Kala Namak 100g")
  expect(titles).toContain("Natco - Kala Namak 300g")
  expect(titles).toContain("Natco - Kalwanji (Nigella) Seeds 300g")
  expect(titles).toContain("Natco - Kasuri Methi Leaves 100g")
  expect(titles).toContain("Natco - Mace Ground 50g")
  expect(titles).toContain("Natco - Marjoram Jar 20g")
  expect(titles).toContain("Natco - Methi Seeds Fenugreek 400g")
  expect(titles).toContain("Natco - Mint Jar 30g")
  expect(titles).toContain("Natco - Mixed Herbs Jar 25g")
  expect(titles).toContain("Natco - Mustard Seeds 400g")
  expect(titles).toContain("Natco - Nutmeg Ground 50g")
  expect(titles).toContain("Natco - Oregano Jar 25g")
  expect(titles).toContain("Natco - Panchpuran (5 Whole Spice) 1kg")
  expect(titles).toContain("Natco - Paprika Powder 400g")
  expect(titles).toContain("Natco - Parsley Jar 25g")
  expect(titles).toContain("Natco - Rosemary Jar 40g")
  expect(titles).toContain("Natco - Saffron 1g")
  expect(titles).toContain("Natco - Sage Jar 25g")
  expect(titles).toContain("Natco - Takmuria (Basil Seeds) 100g")
  expect(titles).toContain("Natco - Tamarind Slab 200g")
  expect(titles).toContain("Natco - Tamarind Wet 400g")
  expect(titles).toContain("Natco - Tandoori Masala Jar 100g")
  expect(titles).toContain("Natco - Turmeric Powder 400g")
  expect(titles).toContain("Natco - White Pepper Ground 100g")
  expect(titles).toContain("Natco - Whole Birdseye Chilli Jar 40g")
  expect(titles).toContain("Natco - Whole Birdseye Chilli Jar 50g")
  expect(titles).toContain("Natco - Yellow Mustard Seeds 300g")

  // TRS spices & herbs
  expect(titles).toContain("TRS Coarse Black Pepper")
  expect(titles).toContain("TRS Coriander Powder (Dhania)")
  expect(titles).toContain("TRS Coriander Seeds (Whole Dhania)")
  expect(titles).toContain("TRS Crushed Chilli")
  expect(titles).toContain("TRS Cumin Powder")
  expect(titles).toContain("TRS Cumin Seeds")
  expect(titles).toContain("TRS Fennel Seeds")
  expect(titles).toContain("TRS Fenugreek Leaves")
  expect(titles).toContain("TRS Fenugreek Seeds")
  expect(titles).toContain("TRS Garlic Powder")
  expect(titles).toContain("TRS Ginger Powder")
  expect(titles).toContain("TRS Green Cardamom")
  expect(titles).toContain("TRS Mango Powder (Amchoor)")
  expect(titles).toContain("TRS Paprika Powder")
  expect(titles).toContain("TRS Pomegranate Powder (Anardana)")
  expect(titles).toContain("TRS Pomegranate Seeds (Anardana Whole)")
  expect(titles).toContain("TRS Tumeric Powder")
  expect(titles).toContain("TRS Whole Cinnamon (Dalchini)")
})

test("Spices — Spice & Herb Jars child", async ({ page }) => {
  await page.goto("/categories/spice-herb-jars"); await page.waitForSelector(CARD, { timeout: 60000 })
  const titles = await page.$$eval(TITLE, (els) => els.map((el) => el.textContent?.trim()).filter(Boolean) as string[])
  console.log(`Spice & Herb Jars: ${titles.length}`)
  titles.forEach((t, i) => console.log(`  ${i + 1}. ${t}`))

  // Count verification
  expect(titles.length).toBeGreaterThanOrEqual(18)

  // --- All 18 Spice & Herb Jars products ---
  expect(titles).toContain("Natco - Black Pepper Ground Jar 100g")
  expect(titles).toContain("Natco - Black Pepper Whole Jar 100g")
  expect(titles).toContain("Natco - Cumin Ground Jar 70g")
  expect(titles).toContain("Natco - Cumin Seeds Jar 100g")
  expect(titles).toContain("Natco - Curry Powder Medium Jar 100g")
  expect(titles).toContain("Natco - Fennel Seeds Jar 100g")
  expect(titles).toContain("Natco - Garlic Powder Jar 100g")
  expect(titles).toContain("Natco - Ground Ginger Jar 70g")
  expect(titles).toContain("Natco - Kalwanji (Nigella) Seeds Jar 100g")
  expect(titles).toContain("Natco - Methi Leaves Jar 10g")
  expect(titles).toContain("Natco - Methi Seeds Jar 100g")
  expect(titles).toContain("Natco - Mustard Seeds Black Jar 100g")
  expect(titles).toContain("Natco - Nutmeg Ground Jar 100g")
  expect(titles).toContain("Natco - Nutmeg Whole Jar 100g")
  expect(titles).toContain("Natco - Paprika Powder Jar 100g")
  expect(titles).toContain("Natco - Tamarind Paste Jar 250g")
  expect(titles).toContain("Natco - Turmeric Powder Jar 100g")
  expect(titles).toContain("Natco - White Pepper Ground Jar 100g")
})

test("Spices — Spice Blends & Mixes child", async ({ page }) => {
  await page.goto("/categories/spice-blends-mixes"); await page.waitForSelector(CARD, { timeout: 60000 })
  const titles = await page.$$eval(TITLE, (els) => els.map((el) => el.textContent?.trim()).filter(Boolean) as string[])
  console.log(`Spice Blends & Mixes: ${titles.length}`)
  titles.forEach((t, i) => console.log(`  ${i + 1}. ${t}`))

  // Count verification
  expect(titles.length).toBeGreaterThanOrEqual(18)

  // --- All 19 Spice Blends & Mixes products ---
  expect(titles).toContain("Natco - All Purpose Seasoning 100g")
  expect(titles).toContain("Natco - All Purpose Seasoning 400g")
  expect(titles).toContain("Natco - Anardana Powder Mangal 100g")
  expect(titles).toContain("Natco - Biryani Masala Mangal 50g")
  expect(titles).toContain("Natco - Chana Masala Mangal 100g")
  expect(titles).toContain("Natco - Chat Masala Mangal 100g")
  expect(titles).toContain("Natco - Chicken Masala Mangal 100g")
  expect(titles).toContain("Natco - Garam Masala 400g")
  expect(titles).toContain("Natco - Meat Masala Mangal 100g")
  expect(titles).toContain("Natco - Mixed Masala Whole 300g")
  expect(titles).toContain("Natco - Pavbhaji Masala Mangal 100g")
  expect(titles).toContain("Natco - Pickle Masala Mangal 125g")
  expect(titles).toContain("Natco - Sambhar Masala Mangal 100g")
  expect(titles).toContain("Natco - Tandoori Masala 400g")
  expect(titles).toContain("Natco - Thecha Chilli Paste 300g")

  // TRS blends
  expect(titles).toContain("TRS Garam Masala")
  expect(titles).toContain("TRS Hot Madras Curry")
  expect(titles).toContain("TRS Mild Madras Curry Powder")
  expect(titles).toContain("TRS Sarson Ka Saag (Spiced Mustard Greens Curry)")
})

test("Spices — Food Colourings & Essences child", async ({ page }) => {
  await page.goto("/categories/food-colourings-essences"); await page.waitForSelector(CARD, { timeout: 60000 })
  const titles = await page.$$eval(TITLE, (els) => els.map((el) => el.textContent?.trim()).filter(Boolean) as string[])
  console.log(`Food Colourings & Essences: ${titles.length}`)
  titles.forEach((t, i) => console.log(`  ${i + 1}. ${t}`))

  // Count verification
  expect(titles.length).toBeGreaterThanOrEqual(18)

  // --- All 19 Food Colourings & Essences products ---
  expect(titles).toContain("Natco - Almond Flavouring Essence 28ml")
  expect(titles).toContain("Natco - Coconut Flavouring Essence 28ml")
  expect(titles).toContain("Natco - Green Food Colouring - Liquid 28ml")
  expect(titles).toContain("Natco - Green Food Colouring - Powder 25g")
  expect(titles).toContain("Natco - Kevda Water 310ml")
  expect(titles).toContain("Natco - Lemon Juice 1 Ltr")
  expect(titles).toContain("Natco - Lemon Juice 500ml")
  expect(titles).toContain("Natco - Lemon Juice with Essential Oil 200ml")
  expect(titles).toContain("Natco - Orange Food Colouring - Liquid 28ml")
  expect(titles).toContain("Natco - Orange Food Colouring - Powder 25g")
  expect(titles).toContain("Natco - Pineapple Flavouring Essence 28ml")
  expect(titles).toContain("Natco - Red Food Colouring - Liquid 28ml")
  expect(titles).toContain("Natco - Red Food Colouring - Powder 25g")
  expect(titles).toContain("Natco - Rose Flavouring Essence 28ml")
  expect(titles).toContain("Natco - Rose Syrup 725ml")
  expect(titles).toContain("Natco - Rose Water 310ml")
  expect(titles).toContain("Natco - Strawberry Flavouring Essence 28ml")
  expect(titles).toContain("Natco - Vanilla Flavouring Essence 28ml")
  expect(titles).toContain("Natco - Yellow Food Colouring - Powder 25g")
})

test("Spices — Sugar & Jaggery child", async ({ page }) => {
  await page.goto("/categories/sugar"); await page.waitForSelector(CARD, { timeout: 60000 })
  const titles = await page.$$eval(TITLE, (els) => els.map((el) => el.textContent?.trim()).filter(Boolean) as string[])
  console.log(`Sugar & Jaggery: ${titles.length}`)
  titles.forEach((t, i) => console.log(`  ${i + 1}. ${t}`))

  // Count verification
  expect(titles.length).toBeGreaterThanOrEqual(4)

  // --- All 4 Sugar & Jaggery products ---
  expect(titles).toContain("Natco - Demerara Sugar 1.5kg")
  expect(titles).toContain("Natco - Demerara Sugar 500g")
  expect(titles).toContain("Natco - Jaggery 500g")
  expect(titles).toContain("Natco - Sugar Candy 375g")
})
